### ISSUE TITLE
I can't use with Garena version

### ISSUE THREAD

**Issue by fudio101** [aPinat/Deceive#1]
At Southeast Asia we use a LOL version run with Garena app, the login is done automatically by the 3rd app so it cannot be opened independently. You can see more here: https://www.garena.vn/gpc

**Comment by aPinat** [comment]
Yes I am aware of that.
However due to authentication happening in Garena Plus and it directly opening the Riot Client/League Client, the way Deceive currently works is incompatible with your launcher.

More info in upstream repo: https://github.com/molenzwiebel/Deceive/issues/17 https://github.com/molenzwiebel/Deceive/issues/91
